# YAML
default: &DEFAULT !BaseParameter
  batch_size: 100
  split_ratio: 0.6
  train_embedding: true
  cell: sru
  init_state_type: var
  dilation: [1, 2, 4, 8, 16, 32]
  num_hidden: 128
  metric: cosine
  num_epoch: 1000
  optimizer: rmsp
  learning_rate: 1.0e-4
  decay_rate: 0.97
  test_interval: 1
  loss: logisitc
  input_data: big.json.gz

development: !BaseParameter
  <<: *DEFAULT
  test_interval: 10
  input_data: toy.json.gz
